-- begin CMS_EXT_COMPANY
alter table CMS_EXT_COMPANY add constraint FK_CMS_EXT_COMPANY_ON_COMPANY_LICENSE_PHOTO foreign key (COMPANY_LICENSE_PHOTO_ID) references SYS_FILE(ID)^
alter table CMS_EXT_COMPANY add constraint FK_CMS_EXT_COMPANY_ON_AUTHORIZATION_LETTER_PHOTO foreign key (AUTHORIZATION_LETTER_PHOTO_ID) references SYS_FILE(ID)^
create index IDX_CMS_EXT_COMPANY_ON_COMPANY_LICENSE_PHOTO on CMS_EXT_COMPANY (COMPANY_LICENSE_PHOTO_ID)^
create index IDX_CMS_EXT_COMPANY_ON_AUTHORIZATION_LETTER_PHOTO on CMS_EXT_COMPANY (AUTHORIZATION_LETTER_PHOTO_ID)^
-- end CMS_EXT_COMPANY
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_EXTCOMPANY foreign key (EXTCOMPANY_ID) references CMS_EXT_COMPANY(ID)^
create index IDX_SEC_USER_ON_EXTCOMPANY on SEC_USER (EXTCOMPANY_ID)^
-- end SEC_USER
